leftnav:
- identifier: ab324243-944d-ab9e-45ac-4f3a00a3f9cf
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: ffebb96b-0743-22bf-1e5f-76372472aa25
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 6c7aaf4e-7ef3-c2bb-db34-adde221493f6
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 30
- identifier: 6e656950-f20c-2da2-8048-9600ef56e312
  name: Readings
  pageRef: /pages/readings
  weight: 40
- identifier: 06c3a5bc-1490-018b-af04-49d8a72bcb9d
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: d051701e-11c7-ba8a-9d77-bf0c8812f9e7
  name: Exams
  pageRef: /pages/exams
  weight: 60
